---
title: "How to implement parameter estimation each week"
author: "Abigail Horn"
date: "3/1/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Updating parameter estimation code (ABC)

### Estimate each parameter’s first values for $week (1)$

- Input:
  - **Prior parameter distributions**: Use the existing distributions of prior parameters in the `prior.par` function.

- Output:
  - The existing paramter estimation code produces the output of the data frame `ABC.par.out`, of dimensions = $# values to save$ X $# of parameters$ (where $# values to save$ = `n_rec` from the ABC model fitting code, which is currently set to 100; we will modify this later). Let's label `ABC.par.out` for $week(1)$ `ABC.par.out_week_1`.
  - We want to put this `ABC.par.out_week_1` data frame into a `list` that is length = $# weeks$ we're estimating the model at. Each entry of this `list` is the `ABC.par.out_week_i` data frame for $week (i)$. Call this `list` something like `week_par_all` [We will need this data frame of values for model simulations] 
  - Save the ***mean values of $week (1)$ parameters*** in a dataframe of dimensions = $# weeks$ X $# parameters$, calling it something like `week_par_mean`. Then $row(i)$ will be the mean value of $week (i)$’s estimated parameters. Thus, if we look across the length of the rows we have the mean time-series for each parameter.  [We will need this for each $week (i+1)^{th}$ parameter estimation]
  - Save the ***standard deviations of $week (1)$ parameters*** in a matrix or data frame of dimensions $# weeks$ X $# parameters$, calling it something like `week_par_sd`. $row(i)$ will be the $sd$ value of $week (i)$’s estimated parameters. [We will need this for each future week’s parameter estimation]

### Estimate each parameter’s first values for $week (2)$

- Input: 
  - First, we will need to read-in the mean value of $week (1)$'s parameters in the data frame `week_par_mean`. Read this in and then adapt the `fn_t_readin_code` file that will convert the $week (1)$'s parameters into the $\alpha(t)$, $\kappa(t)$, $\delta(t)$, $\mu(t)$/$R(t)$, $r(t)$ (t,y) functions over time, which are required to run `seihqdr_generator( . )`. (**Note** that we are currently reading in the $\alpha(t)$, $\kappa(t)$, $\delta(t)$, $\mu(t)$/$R(t)$, $r(t)$ (t,y) functions in from an external .csv file. But now since we are estimating these parameters each week, we don’t need to read those in from the external file — we read them in from our data frame `week_par_mean`.)
  - **Prior parameter distributions**: Use mean estimates from previous $week (1)$ coming from `week_par_mean` as the mean prior values for each parameter. Use the sd of the estimates from `week_par_sd` as the sd of each of the parameters prior distributions.

- Output:
  - Save the `ABC.par.out_week_2` from this week’s parameter values in list entry # 2 of the list `week_par_all` 
  - Save the mean values of $week (2)$’s parameters into row #2 of `week_par_mean`
  - Save the sd values of $week (2)$’s parameters into row #2 of `week_par_sd`

### Move to week 3, and so on.

# 2. Updating model simulation code

- To simulate the model we will use the output from the `list` `week_par_all`
- First, we’ll combine the $j^{th}$ (which is equal to the `n_rec`$^{th}$) estimated value for each parameter from each week, which we’ll take from the list `week_par_all`. To do this I suggest:
  - Concatenate all items in the list `week_par_all` into a single data frame, adding an additional column that saves the label of each week's ID number. This will stack a total # of list entries = $# weeks$ the model is estimated at.
  - Extract the $j^{th}$ entry of each parameter on each week to create the scenario $j$ for each parameter. So essentially here you are creating a dataframe `week_par_sim_j` of dimensions = $# weeks$ X $# parameters$ for each scenario. It will look like the structure of `week_par_mean` actually. In total, you will create `n_rec` number of simulations, or in other words, $j$ = `n_rec`. 
  - Then the model simulation code takes all of those values of those parameters across the full timeseries of the epidemic from `week_par_sim_j` and simulates the model forward over # of iterations.
  - The model is simulated like this over the $j$ scenarios, or in other words, over all $j$ of the `week_par_sim_j` scenarios.
